server:
  address: 0.0.0.0
  port: 8080
  servlet.session.tracking-modes: COOKIE

spring:
  main:
    allow-circular-references: true
  # konfigurasi untuk koneksi db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    # sesuaikan nama database anda dengan di bawah ini
    url: jdbc:mysql://db:3306/tk_apap?useSSL=false&serverTimezone=Asia/Jakarta

    # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
    username: apap_user
    password: password1234!



  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    # pembuatan database (create || create-drop || validate || update)
    hibernate.ddl-auto: create-drop

    show-sql: true



jwt:
  secret: rumahsehat
  expirationMs: 3600000

sso:
  url: https://apap-065.cs.ui.ac.id

